### PR TITLE
Change namespace

### LINKED ISSUE #6: Wrong namespaces
I think your project was created using mongodb samples.

### PR DESCRIPTION
**Pull request by ti24horas**
This will fix #6

### CODE REVIEW

**Comment by ti24horas** [comment]
and this? Please see also #3 and #5 and #6

**Comment by ti24horas** [comment]
Sorry, there was a conflict regarding namespaces.

**Comment by vip32** [comment]
Merged, Hope it is better now

**Comment by ti24horas** [comment]
Is your CI responsible for creating a new nuget package? If so, can you take a look why it's failing? I think it's related with your account.

**Comment by vip32** [comment]
Yes, appveyor should build/publish new nuget. However can't check build logs right now.

**Pull request merged**
