### PR TITLE
Serilog 4

### PR DESCRIPTION
**Pull request by marklam**
Updated package dependencies on LiteDB and Serilog
* Periodic batching is in the core Serilog
* Literate is now the default for Console logging (in test project)

### CODE REVIEW

**Comment by marklam** [comment]
I assume the build failure is build-pipeline related to changing the platforms to match Serilog 4, but I don't have access to see the full build logs.

**Review by vip32 — APPROVED** [review]

**Comment by vip32** [comment]
Yes some frameworks are missing during build. Please remove the .net4 targets,  no support for those. Only core 6, 7, 8. a github actions pipeline will make this more transparent. Lets move away from azure devops pipeline.

**Comment by marklam** [comment]
Is there any reason not to cut the frameworks down to netstandard 2.0?
I had just copied the set that serilog used, for consistency.

**Comment by vip32** [comment]
no particular reason, just don't want to bother with classic stuff (for example pipelines). net6, 7 + 8 will do just fine nowadays. and netstandard 2 of course

**Comment by vip32** [comment]
ah, now i see. net45;netstandard2.0 where the original targets in this repo. let's continue with your proposal. that means the build pipeline needs to be adjusted for .net 6, 7 + 8 (UseDotNet)

**Comment by vip32** [comment]
please rebase from master. build pipeline has been adjusted for new targetframeworks.

**Comment by vip32** [comment]
Serilog 4 does not support net45 anymore, so it can be removed as targetframework. Please also let netstandard2 in there. Build currently fails at restore step due to serilog 4 & net45

**Comment by marklam** [comment]
It takes 3 minutes to fail now, so I guess it's a different problem?

**Comment by vip32** [comment]
build is fine now, however nuget apikey has expired. let me fix that...

**Pull request merged**
